name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-20.04
    env:
      LIBTORCH_VERSION: 1.9.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/libtorch
          key: libtorch-${{ env.LIBTORCH_VERSION }}
        id: cache-libtorch
      - name: Download LibTorch
        if: steps.cache-libtorch.outputs.cache-hit != 'true'
        run: |
          cd ~
          wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-$LIBTORCH_VERSION%2Bcpu.zip
          unzip -q libtorch.zip
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: false
      - name: Build and test with Rake
        run: |
          bundle config build.torch-rb --with-torch-dir=$HOME/libtorch
          bundle install
          bundle exec rake
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
